### ISSUE TITLE
SimpleChildWindow File Load Exception

### ISSUE THREAD

**Issue by CarterAAelect** [punker76/MahApps.Metro.SimpleChildWindow#122]
Hi All,
having a bit of trouble with the SimpleChildWindow (Which is AWESOME!)
after updating to 2.2.0 simplechildwindow fails to open with a File Load Exception, error below;

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Initialization of 'MahApps.Metro.SimpleChildWindow.ChildWindow' threw an exception.' Line number '61' and line position '40'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at AssetTracking.Controls.UserSettings.InitializeComponent() in V:\Software\AssetTracking\AssetTracking\Controls\UserSettings.xaml:line 1

Inner Exception 1:
FileLoadException: Could not load file or assembly 'MahApps.Metro, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

** Have tried updating several different projects all with the same result, once I get into the 2.x the child window fails, also tried starting with a new project.

I'm sure I'm missing something, I'm just not seeing it.

any help would be greatly apricated
thanks, carter

![Capture1](https://user-images.githubusercontent.com/44813575/89686589-7b717480-d8b3-11ea-80ac-c62169a452b8.JPG)
![Capture2](https://user-images.githubusercontent.com/44813575/89686591-7ca2a180-d8b3-11ea-949c-7942c1fb7b0c.JPG)

.

**Comment by timunie** [comment]
Hi @CarterAAelect 
Please check your version of SimpleChildWindow. Right now it needs to be the latest prerelease as in MahApps.Metro there were a lot of breaking changes.

Happy coding
Tim

**Comment by CarterAAelect** [comment]
Augggg, Brian dead, I forgot pre-release was turned off.
Thank you! Sorry!

**Comment by timunie** [comment]
@CarterAAelect you are welcome. If your issue is solved please remember to close this issue. Thx.

**Comment by eliezeralmeida** [comment]
I solved it by installing version 2.0.0-alpha0043. Thanks for the topic :)
